### ISSUE TITLE
Retrofit 2.0 support

### ISSUE THREAD

**Issue by Diolor** [andretietz/retroauth#15] opened 2015-10-24 21:50 UTC
Retrofit 2.0 non beta should be anytime soon.
Would be nice to be supported :)

**Comment by andretietz** [comment] 2015-10-25 14:29
I'm working on it. Created a branch already. I am not sure that it'll be supported by retroauth itself, since it's a bit easier to do somthing like that, as additional Adapter for retrofit2.

**Comment by xiaolongyuan** [comment] 2016-01-18 04:31
+1

**Comment by xiaolongyuan** [comment] 2016-01-18 04:38
Retrofit2 update to use the OkHttp 3
https://github.com/square/retrofit/tree/parent-2.0.0-beta3

**Comment by andretietz** [comment] 2016-01-18 13:00
Even if it does not seem like it, since I havn't updated anything in my retrofot2 branch, I am working on it. Right now I am searching for a hook into retrofit2, as you can follow here.
https://github.com/square/retrofit/issues/1422

If that's solved there's nothing keeping me from implementing it.
It will be a complete different version, so it won't be downwards compatible, but it will be some kind of a "plugin" for retrofit2

**Comment by andretietz** [comment] 2016-01-22 09:00
Created a pull-request for it:
https://github.com/square/retrofit/pull/1507

**Comment by xiaolongyuan** [comment] 2016-01-22 09:02
good ! keep an eye

**Comment by andretietz** [comment] 2016-02-26 08:45
Sadly this feature has been defered in the retrofit specs. It's planned for the 2.1 milestone.
I'll start creating a beta, without this feature. This is sad, since it'll look a bit uglier then. You'll have to use the "@Header" annotation from retrofit instead of "@Authenticated"

What do you think?
@xiaolongyuan @Diolor

**Comment by Diolor** [comment] 2016-02-26 23:00
If I understood correctly, I think it will be a bit confusing to relate a pre-request action (authentication) with a http request component (headers).

**Comment by xiaolongyuan** [comment] 2016-03-04 05:14
I think it is important to consider and retrofit 2.0 integration. "@Authenticated" as a new feature.

**Comment by xiaolongyuan** [comment] 2016-03-21 01:41
Retrofit 2.0 is release!

<dependency>
  <groupId>com.squareup.retrofit2</groupId>
  <artifactId>retrofit</artifactId>
  <version>2.0.0</version>
</dependency>
or Gradle:

compile 'com.squareup.retrofit2:retrofit:2.0.0'

**Comment by andretietz** [comment] 2016-03-22 15:12
Here an update:

Since my PR was not accepted, I wrapped my head around retrofit 2, to find a good solution.

I found one. Now I just need time to implement it.
I can assure you, that there will be an update soon. It (of course) won't be compatible to retroauth 1.0.4 and below. I guess, I'll try to go with retrofit version numbers, lets see how that works out.

**Comment by xiaolongyuan** [comment] 2016-03-27 09:47
good

**Comment by andretietz** [comment] 2016-03-29 14:55
I got examples working for java(fx just to show that it's not android dependent) and android. Additionally I removed the rxjava dependency.

It still looks experimental and is not fully functional, but I'll add it to the repository soon, as some kind of alpha/beta version, if you'ld like that

**Comment by andretietz** [comment] 2016-03-30 20:58
Not finished yet, but you can take a look already:
https://github.com/andretietz/retroauth/tree/feature/rebuild

Ideas and suggestions are welcome, now is the time todo so.

**Comment by xiaolongyuan** [comment] 2016-04-07 07:32
So good!

**Comment by andretietz** [comment] 2016-04-25 11:48
Snapshots available.

Add:

    maven { url('https://oss.jfrog.org/artifactory/oss-snapshot-local') }

as maven repository and add this dependency

    compile 'com.andretietz.retroauth:retroauth-android:2.0.0-SNAPSHOT' # (or retroauth-core for java only)

**Comment by andretietz** [comment] 2016-04-30 15:38
Fixed the javafx implementation as well, added google instead of github login, since google is using refresh tokens.
Tokens can be automatically refreshed.

**Comment by xiaolongyuan** [comment] 2016-05-22 10:30
When the final version ?

**Comment by andretietz** [comment] 2016-05-30 04:59
working on it, there are still some issues

**Comment by xiaolongyuan** [comment] 2016-05-30 05:02
Good job
What problem?

**Comment by andretietz** [comment] 2016-06-02 16:15
I had to test, what happens, when executing multiple requests with invalid request tokens. It looks just fine.
I will update the readme files and the documentation to prepare the release

**Comment by xiaolongyuan** [comment] 2016-06-03 01:11
Problems caused by the process ?

AccountManager operation is asynchronous

**Comment by andretietz** [comment] 2016-06-10 06:04
No, the problem is more related to:

If you fire 5 authenticated requests at once (and the token is invalid), the loginactivity opens 5 times. To avoid this, I'll add optional request blocking per token type (since another token type doesn't need to be blocked while the otherone is newly requested).

After I've done this, there will be a release

**Comment by andretietz** [comment] 2016-06-11 17:11
prefinal snapshot released. No code changes required if you're coming from the previous one.
You have an additional option when building your Retrofit object to enableLocking.
If this is set to "true" only one authenticated request is will be executed at a time. This is a very pessimistic implementation (as it was in 1.0.4 as well), to avoid sending requests, if you know that it would fail into a 401 i.e. (depending a bit on your implementation)

* readme file from the main project updated

**Comment by andretietz** [comment] 2016-06-12 19:33
Found another cool feature I wanted to add. Hope you like it:

No Activity/Application/Context required anymore for creating the AndroidAuthenticationHandler

            Retrofit retrofit = new Retroauth.Builder<>(new AndroidAuthenticationHandler(provider))
                .baseUrl("https://www.googleapis.com/")
                .client(httpClient)
                .addConverterFactory(MoshiConverterFactory.create())
                .build();

this is it now! Pushing new snapshot today

**Comment by Diolor** [comment] 2016-06-12 20:12
that's pretty nice! Will it pop up the LoginActivity using the AndroidAuthenticationHandler's Context?

**Comment by andretietz** [comment] 2016-06-13 11:20
It will popup the LoginActivity anyways, yes!

**Comment by andretietz** [comment] 2016-06-14 08:00
Final version live:

    compile 'com.andretietz.retroauth:retroauth-android:2.0.0'

I'll close this issue

**Closed by andretietz** 2016-06-14 08:00 UTC

**Comment by xiaolongyuan** [comment] 2016-06-14 10:53
good ！Stable yet?
